added action

diff --git a/.github/workflows/lighthouse-action.yml b/.github/workflows/lighthouse-action.yml
--- a/.github/workflows/lighthouse-action.yml
+++ b/.github/workflows/lighthouse-action.yml
@@ -1,22 +1,20 @@
-name: CI
+name: Build project and Run Lighthouse CI
 on: [push]
 jobs:
   lhci:
-    name: Lighthouse
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
       - name: Use Node.js 10.x
         uses: actions/setup-node@v1
         with:
           node-version: 10.x
       - name: npm install, build
         run: |
-          npm install
+          yarn
           npm run build
       - name: run Lighthouse CI
         run: |
           npm install -g @lhci/cli@0.8.x
-          lhci autorun
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
